### ISSUE TITLE
Criar função para gerar a resposta em frequência

### ISSUE THREAD

**Issue by dferruzzo** [dferruzzo/mavsdk-python#11]
# Objetivo 

Criar uma função que receba com entrada o arquivo `ulg` e o nome do ângulo sendo testado, por exemplo:

`resposta_freq(arquivo='ulogs/log_13_2024-9-16-08-21-12.ulg', angulo='roll')`

O arquivo `ulg` contem os dados de teste de atitude utilizando o modo `offboard`, para o teste utilizo o script `offboard_attitude.py`.
 
A saída da função é:

- Os vetores de dados desejados recortados.
- Os gráficos de atitude, taxa e controle.
- A FFT dos sinais de controle e de taxa (gráficos e dados).
- A resposta em frequência de amplitude e de fase (gráficos e dados).

# To-Do:

- [x] Ler os dados do arquivo `ulg`.
- [x] Identificar os instantes quando inicia o modo `Offboard` e o modo `RTL` (Return-to-land). Nessa janela será feita o recorte dos dados.

Obter e recortar os dados de:

- [x] Atitude correspondente ao parâmetro de entrada.
- [x] A Velocidade angular correspondente ao ângulo.
- [x] O sinal de controle dos motores (quadro sinais).
- [x] Gerar o sinal de controle apropriado.
- [x] Gerar as FFT
- [x] Gerar a Resposta em frequência.

**Comment by dferruzzo** [comment]
Usando 

`PX4_SYS_AUTOSTART=4001 PX4_GZ_MODEL_POSE="0,2,0,0,0,0" PX4_SIM_MODEL=gz_x500 ./build/px4_sitl_default/bin/px4`

**Comment by dferruzzo** [comment]
The frequency response looks inconclusive, specially the phase diagram. This may be because I'm comparing the FFT of the output and input signals. 

![Image](https://github.com/user-attachments/assets/a9abe415-c24c-4070-a28a-b211e829c93b)

The input is a impulse-like signal.

I'll try another aproach. I'll apply a single-frequency tone, and prepare a function to:

- [ ] Open and read de file
- [ ] Clip the data 
- [ ] Compute  the freq, amplitude and phase
- [ ] Output the freq, the Bod point Modulus and phase.

**Comment by dferruzzo** [comment]
Try with a sweep signal.
